server:
  port: 8285

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: device-service
          uri: lb://device-service
          predicates:
            - Path=/devices/**
          filters:
            - PrefixPath=/api/v1
            - AuthFilter
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/api/v1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  prefix: Bearer